### ISSUE TITLE
1.0.0 / 1.0.2 packaged without surrounding folder cannot be installed

### ISSUE THREAD

**Issue by jlkDE** [greyaz/ThemeRevision#1]
Hey,

first I want to thank you for the theme, my team and I really enjoyed the 0.8.0 version so far and I am really curios about the dark theme.
When I tried to install version 1.0.0 or 1.0.2 from the plugin repository nothing seemed to happen, however I got critical errors from Kanboard afterwards as the surrounding folder (named `ThemeRevision` in the 0.8.0 archive) seems to be missing so that the packaged contents are unpacked directly into the plugin directory.
Manually creating the folder or cloning from `git` into the so named directory seems to work too, but I got another error afterwards.

**Comment by greyaz** [comment]
Fixed, thank you for your report.
