### ISSUE TITLE
和Group assign一起使用时, 分配任务的人显示不全

### ISSUE THREAD

**Issue by neotaburiss** [greyaz/ThemeRevision#11]
![image](https://user-images.githubusercontent.com/78628322/202466770-ea8e76f7-0c88-4b51-a9b8-40d19da9774d.png)
如图, 显示分配任务的组和其他分配的人只能显示两个字符,比较不直观,是否可以在插件里面规定下,背景的长度和字符串长度一样(原版就是这样的)

另外这里提一个功能请求,有没有可能直接可以在kanboard里设置每个一个任务卡片的高度(宽度是自动根据页面分栏来计算的),然后其他元素自动根据比例调整位置
因为感觉现有的任务卡片,空的地方还比较多...一个页面上显示的任务卡片数量还可以更多(不用频繁的滚动)

**Comment by greyaz** [comment]
收到。
第一个问题，我会在下个版本里修改一下。
第二个问题，有一点没太明白如果高度固定的话，超出高度的信息准备怎么处理呢？

**Comment by greyaz** [comment]
第二个问题，我大概知道你想法了。下一版本里我会尝试一下。内容少的时候，卡片更紧凑。

**Comment by greyaz** [comment]
@neotaburiss，两个问题我都优化了。
第一个问题，组名现在不会被折叠了。第二个问题，如果标题短于一整行，则分类和标签会尝试挤到标题行内。会比原来少一行。
等合并到官方后，可以试试看。
