### ISSUE TITLE
Show column task limit on board

### ISSUE THREAD

**Issue by helioguardabaxo** [greyaz/ThemeRevision#12]
Hi, @greyaz!

This theme is clean and beautiful. I like it.

I notice that column task limit doesn't showed on board neither a color background when limit is target.
![Screenshot 2022-11-22 at 09-01-13 Projeto Teste](https://user-images.githubusercontent.com/24301085/203314655-1ecb7f0a-b829-4684-8fd5-62fad71ad17f.png)

Native theme looks like:
![Screenshot 2022-11-22 at 09-03-23 Projeto Teste](https://user-images.githubusercontent.com/24301085/203314832-df58049e-e7fd-48c9-979b-ddd0417d3627.png)

Do you intend to implement it? Maybe just values on column title would be concise with theme.

Btw
I don't know if it's possible to implement a way to select or not this info will showed on board. Would be interesting if other info on cards (dates, priorities, metadata, etc.) would be optional.

Thanks!

**Comment by greyaz** [comment]
Thank you @helioguardabaxo 
I marked this issue as new features. I will try to implement your ideas in future releases.

**Comment by helioguardabaxo** [comment]
Great! :smile: 
Thanks!

**Comment by greyaz** [comment]
@helioguardabaxo 
This feature has been implemented in the newest release (1.1.9), please have a try after being merged into the official repository.

**Comment by helioguardabaxo** [comment]
@greyaz 
Great job! It's working fine.
Thanks very much!
