### ISSUE TITLE
Favicon doesn't show when kanboard is installed in subdir

### ISSUE THREAD

**Issue by Dennis14e** [greyaz/ThemeRevision#13]
Hi,

thanks for the nice theme, however there is a problem when kanboard is installed in a subdirectory. Since the favicon is an absolute path, the file cannot be found.

https://github.com/greyaz/ThemeRevision/blob/52a6170ce862113490d103dc424d58f476105fc8/Asset/dev/js/main.js#L8
https://github.com/greyaz/ThemeRevision/blob/52a6170ce862113490d103dc424d58f476105fc8/Asset/dev/js/main.js#L14

**Comment by greyaz** [comment]
Thank you @Dennis14e，I will fix it in in a futrue release.

**Comment by greyaz** [comment]
@Dennis14e ,
This issue should be fixed in the newest release (1.1.9), please have a try after being merged into the official repository and tell me the result.
