### ISSUE TITLE
Question... is this how it's meant to look?

### ISSUE THREAD

**Issue by soopermodel** [greyaz/ThemeRevision#15]
I can't really say it looks okay.
![image](https://user-images.githubusercontent.com/32681723/209267595-40430264-cfce-4dd1-b5c7-6f64335064fc.png)
![image](https://user-images.githubusercontent.com/32681723/209267627-03b34378-396c-48be-9d45-db6cfebb1bfa.png)

**Comment by greyaz** [comment]
Hi @chaeyan ,

Yes, this is what it looks like in dark mode. If you do not like the default color, you can customize it in the settings page. Or feel free to tell me your advice.

**Comment by marlov8** [comment]
Is this empty space in top bar and space before column headers normal? if yes, can you provide a setting to change this behavior? Can user customize it by CSS?

<img width="1977" height="164" alt="Image" src="https://github.com/user-attachments/assets/04233e57-ca5e-4e56-81e1-a32ba63ffdc6" />

**Comment by marlov8** [comment]
[This ](https://github.com/kenlog/KangarooJump/issues/7) solved first issue
