### ISSUE TITLE
请教个问题，kanboard插件如何支持中文显示？

### ISSUE THREAD

**Issue by yangzheng6678** [greyaz/ThemeRevision#16]
想汉化一下其他的插件来使用，请问您除了添加locale里的翻译文件，还需要在哪添加配置才能使中文显示出来，谢谢了。

**Comment by greyaz** [comment]
一般来说，如果插件已经支持了多语言，则直接增加对应语言的翻译文件即可。如果无效，可能是因为插件本身就没有考虑多语言。可以看一下这个插件的`plugin.php`文件中的`onStartup()`函数中有没有加载翻译文件的类似代码：
```php
Translator::load($this->languageModel->getCurrentLanguage(), __DIR__.'/Locale');
```

**Comment by yangzheng6678** [comment]
已经添加了这句话，在Locale里也建立了zh_CN文件夹，编写翻译文件后，如果填写翻译为中文文字，就显示空白，填写英文则正常显示。
public function onStartup()
    {
        Translator::load($this->languageModel->getCurrentLanguage(), __DIR__.'/Locale');
    }

translations.php文件：
```php
<?php
return array(
  //
  // GENERAL
  //
  'Add Global Tag' => '添加全局标签',
);
```

**Comment by greyaz** [comment]
首先看一下代码头部有没有引入Translator包，其次确认Add Global Tag是否支持被翻译，能够翻译的内容需要用t函数或者e函数包裹。详情可以看一下kanboard的官方文档：
https://docs.kanboard.org/v1/dev/translations/

**Comment by yangzheng6678** [comment]
谢谢指导，我先试一下。
