### ISSUE TITLE
Undefined variable $color_diffs

### ISSUE THREAD

**Issue by sashaoshurkov** [greyaz/ThemeRevision#21]
Dear @greyaz 

Kanboard v1.2.27 (docker)
ThemeRevision 1.1.11

PHP warning shows in Theme Settings:
```
Warning: Undefined variable $color_diffs in /var/www/app/plugins/ThemeRevision/Template/settings/configs/color_update_notice.php on line 4

Warning: foreach() argument must be of type array|object, null given in /var/www/app/plugins/ThemeRevision/Template/settings/configs/color_update_notice.php on line 4
```
![Screenshot from 2023-03-16 08-17-40](https://user-images.githubusercontent.com/1682848/225521737-cfbfca43-ed99-4e90-b104-2d9af0c304f6.png)

**Comment by greyaz** [comment]
Fix it in the next version: 1.1.12
