### ISSUE TITLE
[非bug] 功能和使用方法咨询

### ISSUE THREAD

**Issue by neotaburiss** [greyaz/ThemeRevision#3]
很高兴又看到简中用户使用kanboard,有看到作者的kanboard已经是生产力阶段,并且和我们公司的业务流程有点像

不知道作者有没有使用自动动作,就是自动变颜色,自动移动栏位的,能否分享下... 我们这里自动动作一直设置不好(特别是跨部门的)

**Comment by greyaz** [comment]
你好，我这边因为有专门的项目管理人员，所以跨部门的问题是人工处理的，我们的流程里会有待流转一栏，用于处理跨部门流转。自动动作配合了group assign主要用于通知相关环节的其他人员。

**Comment by greyaz** [comment]
感觉这个作为open issue讨论有点不太合适，我先关闭了，不过有问题的话你还是可以在这里留言的，我能回就回～
