### ISSUE TITLE
After login kanboard returns JSON { "reload": false, "setting" "" } instead of the dashboard

### ISSUE THREAD

**Issue by ghost** [greyaz/ThemeRevision#4]
When using the plugin, kanboard returns JSON after logging-in
{
  "reload": false,
  "setting": ""
}
Looking into the files, I suspect $userscheme should not be empty, but I don't what that is about. I am able to login, by removing the controller and the action reference in the url. This is a workaround though, but would like to know how this can be fixed.

**Comment by greyaz** [comment]
@hoendehaan  Thank you for your feedback. I'll try to fix it asap.
You can set the option `$themeRevisionConfig['color scheme']` in config file to `'light'` temporarily to avoid the issue.

**Comment by greyaz** [comment]
@hoendehaan, this issue should be fixed. Please clone the main branch and have a try.
