### ISSUE TITLE
Adding a custom font

### ISSUE THREAD

**Issue by dangerstudios** [greyaz/ThemeRevision#6]
how would this be done?

thanks in advance

**Comment by greyaz** [comment]
You can find fonts related codes in the file `Asset/dev/basics.css` line 8.
Please follow the instruction here to edit:
https://github.com/greyaz/ThemeRevision#other-styles

**Comment by dangerstudios** [comment]
ok cool, I've got that in there, how do I link it to the font?
`--style-fontfamily: "IBM Plex Mono"; /* "IBM Plex Sans", "Helvetica Neue", Helvetica, Arial, sans-serif; */`

**Comment by greyaz** [comment]
Your code should work after refresh the browser if you have installed this font in your computer.
But "IBM plex Mono" is not a system default font, I recommend you approach it in another way:
1. Goto `Settings > Application settings` in Kanboard
2. Paste the codes below into "Custom Stylesheet":
```
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital@0;1&display=swap');

body{
font-family: 'IBM Plex Mono', monospace !important;
}
```

**Comment by dangerstudios** [comment]
> 

ah ok, I'll give it a go , cheers!

**Comment by dangerstudios** [comment]
> Your code should work after refresh the browser if you have installed this font in your computer. But "IBM plex Mono" is not a system default font, I recommend you approach it in another way:
> 
> 1. Goto `Settings > Application settings` in Kanboard
> 2. Paste the codes below into "Custom Stylesheet":
> 
> ```
> @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital@0;1&display=swap');
> 
> body{
> font-family: 'IBM Plex Mono', monospace !important;
> }
> ```

yes totally works now, cheers!

**Comment by greyaz** [comment]
👍
