### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by dangerstudios** [greyaz/ThemeRevision#7]
Great Theme!!

### **Adding options to the theme settings:**

- [ ] Custom fonts from google cdn.
- [ ] Update to the latest Font Awesome. 
- [ ] Alternate between Font Awesome & Google Material Icons.

**Comment by greyaz** [comment]
Thank you @dangerstudios . 
Actually, I had tried to update the Font Awesome icons, but the final effect was worse than my imagination. 
I will consider your requests in the future updates.

**Comment by greyaz** [comment]
@dangerstudios Feature 1 and 3 have been supported in the last release [1.1.1](https://github.com/greyaz/ThemeRevision/releases/tag/1.1.1).

**Comment by greyaz** [comment]
![image](https://user-images.githubusercontent.com/398356/193267821-f92d6b78-f4ea-4b39-94ea-163db8427186.png)

**Comment by dangerstudios** [comment]
AWESOME!!!
