### ISSUE TITLE
Header Logo via Customizer Plugin not possible

### ISSUE THREAD

**Issue by BuschSid** [greyaz/ThemeRevision#8]
Hey!
So I am using Customizer to insert custom pictures.
But as long as ThemeRevision is installed, I only see the standard KB Logo.
In the Login screen I see both (lol), first my custom Logo and beneath it the standard KB logo.

Where do I change it so I only see my custom logo, do I have to edit the css file?
Where do I find the css in my Portainer file tree?

Regards 
Tobias

**Comment by greyaz** [comment]
Hello @BuschSid,

ThemeRevision may not compatible with Customizer currently, but I can add it to my todo list. 

If you want to change the logo, you can just log into you server, goto the directory `your_kanboard_root/assets/img` and replace the file `favicon.png`.

ThemeRevision utilize this file as the head logo.

**Comment by BuschSid** [comment]
Hey greyaz,

thanks for the quick answer.
I changed the favicon.png and it worked.

I have one more problem, the logo on the login screen is not centered but pretty ugly to the left.

***@***.***

Any idea what I could do?

Regards,
Tobias

**Comment by greyaz** [comment]
@BuschSid, you can do this:

1. Goto Settings -> Application Settings -> Custom Stylesheet
2. Paste the following codes into the textarea:
```css
.TR .form-login {
    text-align: center;
}
.TR .form-login>form {
    text-align: left;
}
```

**Comment by greyaz** [comment]
Hi @BuschSid , 

In the newest release (1.1.6), the logo in the login page has been centered by default.
