### ISSUE TITLE
和[SubtaskDescription]插件一起使用时，子任务标题方格显示的内容溢出

### ISSUE THREAD

**Issue by neotaburiss** [greyaz/ThemeRevision#9]
![image](https://user-images.githubusercontent.com/78628322/200879367-7615700d-f54d-45a3-8ae8-75402028989e.png)
和[SubtaskDescription](https://github.com/Shaun-Fong/SubtaskDescription)和插件一起使用时，子任务标题方格显示的内容溢出

**Comment by greyaz** [comment]
@neotaburiss 收到，谢谢。我之后适配一下

**Comment by greyaz** [comment]
@neotaburiss 该问题已经尝试在新的发布版本（1.1.6）中修复了。请等待合并到官方后更新看看。
